name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Deploy backend
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key_path: "devops/cajitasdeamor.pem"
        script: |
          cd /home/projects/cajitasdeamor-services
          sudo git checkout main
          echo 'webos'
          sudo git pull
          echo 'webos 2'
          sudo systemctl stop cajitas-services
          echo 'webos3'
          sudo systemctl start cajitas-services
          sudo systemctl enable cajitas-services
          echo 'webos5'
    
